'use client'

import { useState } from 'react'
import {
  Activity, Target, Gauge, Timer, Zap, ChevronDown, ChevronUp,
  CheckCircle2, AlertTriangle, DollarSign, Users, TrendingDown,
  Cpu, ArrowRight, Database, Brain, Mail, Phone, Globe, FileSpreadsheet,
  BarChart3, RefreshCw, Megaphone, Send, Eye
} from 'lucide-react'

// ── Performance Metrics ──
// Source: ml/model_metadata.json (regenerated by scripts/train_model.py)
// Reported at the F1-optimal decision threshold (0.40), tuned via PR-curve.
const performanceMetrics = [
  { label: 'AUC-ROC', value: '0.73', icon: Target },
  { label: 'Accuracy', value: '0.68', icon: Activity },
  { label: 'Precision', value: '0.41', icon: Gauge },
  { label: 'Recall', value: '0.66', icon: Eye },
  { label: 'F1 Score', value: '0.50', icon: BarChart3 },
  { label: 'Threshold', value: '0.40', icon: Timer },
  { label: 'Latency', value: '0.3ms', icon: Zap },
]

// ── Baseline Comparison ──
// All numbers measured on the same 2,000-row test set.
// XGBoost reported at the F1-optimal threshold; LR and rule-based at their defaults.
const baselineModels = [
  { model: 'XGBoost (primary)', auc: '0.73', precision: '0.41', recall: '0.66', f1: '0.50', highlight: true },
  { model: 'Logistic Regression', auc: '0.72', precision: '0.39', recall: '0.66', f1: '0.49', highlight: false },
  { model: 'Rule-based Heuristic', auc: '0.69', precision: '0.49', recall: '0.55', f1: '0.52', highlight: false },
]

// ── Go/No-Go ──
// Targets reflect a recall-prioritized CVM use case, where false negatives (missed churners)
// cost materially more than false positives (a low-cost retention offer to a stable subscriber).
const goNoGoRows = [
  { metric: 'AUC-ROC', target: '>= 0.65', actual: '0.73', pass: true },
  { metric: 'Recall', target: '>= 0.50', actual: '0.66', pass: true },
  { metric: 'Precision', target: '>= 0.40', actual: '0.41', pass: true },
  { metric: 'F1', target: '>= 0.45', actual: '0.50', pass: true },
  { metric: 'Latency', target: '< 5s', actual: '0.3ms', pass: true },
]

// ── Business Impact ──
const businessMetrics = [
  { label: 'Subscriber base', value: '95,000,000', source: 'Indosat FY2024', icon: Users },
  { label: 'Monthly churn rate', value: '3.5%', source: 'GSMA Intelligence 2023', icon: TrendingDown },
  { label: 'Churners flagged/month', value: '2,194,500', source: 'Calculated (95M x 3.5% x 0.66 recall)', icon: AlertTriangle },
  { label: 'Retention rate with offer', value: '25%', source: 'Industry benchmark', icon: Target },
  { label: 'Subscribers retained/month', value: '548,625', source: 'Calculated', icon: CheckCircle2 },
  { label: 'Revenue saved/month', value: '$4.4M', source: 'At $8.50 avg ARPU x partial 12-mo LTV factor', icon: DollarSign },
  { label: 'Annual impact', value: '~$52.7M', source: 'Calculated ($4.4M x 12)', icon: DollarSign },
]

// ── Edge Cases ──
// Stress numbers are projected impacts (not measured) — they describe directional
// degradation under each scenario. Normal row reflects measured XGBoost performance.
const edgeCases = [
  {
    title: 'Competitor Mass Promo',
    description: 'When a competitor launches aggressive promotions (e.g., free data for 3 months), the model over-predicts churn as it conflates promotional sensitivity with genuine churn intent. Sudden shifts in usage patterns flood the model with false positives.',
    normal: { auc: 0.73, precision: 0.41, recall: 0.66, f1: 0.50 },
    stress: { auc: 0.60, precision: 0.30, recall: 0.78, f1: 0.43 },
  },
  {
    title: 'Aggressive Pricing Change',
    description: 'A sudden internal pricing change (e.g., 30% tariff increase) makes ARPU signals unreliable. The model trained on stable pricing cannot distinguish voluntary churn from price-shock churn, and ARPU-based features become noise.',
    normal: { auc: 0.73, precision: 0.41, recall: 0.66, f1: 0.50 },
    stress: { auc: 0.56, precision: 0.28, recall: 0.70, f1: 0.40 },
  },
  {
    title: 'Regulatory SIM Re-registration',
    description: 'Government-mandated SIM re-registration causes mass temporary deactivations. The tenure signal is corrupted as long-standing subscribers appear as new users after re-registration, and inactivity periods are misread as churn signals.',
    normal: { auc: 0.73, precision: 0.41, recall: 0.66, f1: 0.50 },
    stress: { auc: 0.62, precision: 0.34, recall: 0.62, f1: 0.44 },
  },
  {
    title: 'Dual-SIM Behavior',
    description: 'In markets with high dual-SIM adoption, low usage on a secondary SIM is misread as churn risk. The model cannot distinguish a dormant secondary SIM from a subscriber about to leave, inflating false positive rates significantly.',
    normal: { auc: 0.73, precision: 0.41, recall: 0.66, f1: 0.50 },
    stress: { auc: 0.58, precision: 0.32, recall: 0.65, f1: 0.43 },
  },
]

// ── Technology Stack ──
const techStack = [
  { component: 'Predictive Model', technology: 'XGBoost (scikit-learn, production: LightGBM)' },
  { component: 'Generative AI', technology: 'Claude Sonnet 4 (Anthropic SDK)' },
  { component: 'Frontend', technology: 'Next.js 14, React, Tailwind CSS' },
  { component: 'Backend API', technology: 'Next.js API Routes (serverless)' },
  { component: 'Email Delivery', technology: 'Gmail SMTP (nodemailer)' },
  { component: 'Voice Call', technology: 'Twilio Voice API (text-to-speech)' },
  { component: 'Deployment', technology: 'Vercel (auto-deploy from GitHub)' },
  { component: 'Data', technology: '10,000 synthetic subscribers (CSV)' },
]

// ── AI Factory Architecture steps ──
const architectureSteps = [
  { label: 'Data Sources', icon: Database, desc: 'CRM, CDR, billing, NPS' },
  { label: 'Ingestion', icon: FileSpreadsheet, desc: 'ETL pipeline' },
  { label: 'Feature Engineering', icon: Cpu, desc: '18 behavioral features' },
  { label: 'Model Training', icon: Brain, desc: 'XGBoost / LightGBM' },
  { label: 'Scoring', icon: Target, desc: 'Risk probability 0-1' },
  { label: 'Campaign Generation', icon: Megaphone, desc: 'Claude Sonnet 4' },
  { label: 'Delivery', icon: Send, desc: 'Email, SMS, Voice' },
  { label: 'Outcome Tracking', icon: BarChart3, desc: 'Retention metrics' },
  { label: 'Feedback / Retraining', icon: RefreshCw, desc: 'Model refresh cycle' },
]

export default function ModelEvaluation() {
  const [expandedEdgeCase, setExpandedEdgeCase] = useState<number | null>(null)
  const [showBusinessBreakdown, setShowBusinessBreakdown] = useState(false)

  return (
    <div className="space-y-6">

      {/* ── 1. Performance Metrics ── */}
      <div>
        <div className="text-[10px] font-semibold text-brand-400 tracking-wider uppercase mb-1">Performance Metrics</div>
        <p className="text-xs text-gray-600 mb-4">XGBoost classifier trained on 10,000 subscribers with 18 behavioral and demographic features.</p>
        <div className="grid grid-cols-2 sm:grid-cols-3 lg:grid-cols-7 gap-3">
          {performanceMetrics.map((m) => (
            <div key={m.label} className="bg-gray-50 border border-gray-200 rounded-xl p-4 text-center min-w-0 overflow-hidden">
              <m.icon className="w-4 h-4 text-brand-400 mx-auto mb-2" />
              <div className="text-xl font-bold text-gray-900 leading-tight tabular-nums truncate">{m.value}</div>
              <div className="text-[10px] text-gray-600 mt-1 leading-tight truncate">{m.label}</div>
            </div>
          ))}
        </div>
      </div>

      {/* ── 2. Confusion Matrix + 3. Baseline Comparison ── */}
      <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
        {/* Confusion Matrix */}
        <div className="bg-gray-50 border border-gray-200 rounded-xl p-5">
          <div className="text-[10px] font-semibold text-brand-400 tracking-wider uppercase mb-1">Confusion Matrix</div>
          <p className="text-xs text-gray-600 mb-4">Prediction outcomes on the 2,000-sample test set.</p>
          <div className="grid grid-cols-2 gap-2">
            <div className="bg-green-500/10 border border-green-500/20 rounded-lg p-4 text-center">
              <div className="text-[10px] text-green-600/60 uppercase tracking-wider mb-1">True Negative</div>
              <div className="text-2xl font-bold text-green-600">1,023</div>
            </div>
            <div className="bg-red-500/10 border border-red-500/20 rounded-lg p-4 text-center">
              <div className="text-[10px] text-red-600/60 uppercase tracking-wider mb-1">False Positive</div>
              <div className="text-2xl font-bold text-red-600">480</div>
            </div>
            <div className="bg-red-500/10 border border-red-500/20 rounded-lg p-4 text-center">
              <div className="text-[10px] text-red-600/60 uppercase tracking-wider mb-1">False Negative</div>
              <div className="text-2xl font-bold text-red-600">168</div>
            </div>
            <div className="bg-green-500/10 border border-green-500/20 rounded-lg p-4 text-center">
              <div className="text-[10px] text-green-600/60 uppercase tracking-wider mb-1">True Positive</div>
              <div className="text-2xl font-bold text-green-600">329</div>
            </div>
          </div>
          <div className="mt-3 grid grid-cols-2 gap-2 text-center text-[10px] text-gray-600">
            <div>Predicted: No Churn</div>
            <div>Predicted: Churn</div>
          </div>
        </div>

        {/* Baseline Comparison */}
        <div className="bg-gray-50 border border-gray-200 rounded-xl p-5">
          <div className="text-[10px] font-semibold text-brand-400 tracking-wider uppercase mb-1">Baseline Comparison</div>
          <p className="text-xs text-gray-600 mb-4">Three models evaluated on the same test set.</p>
          <div className="overflow-x-auto">
            <table className="w-full text-xs">
              <thead>
                <tr className="border-b border-gray-200">
                  <th className="text-left text-gray-600 font-medium pb-2">Model</th>
                  <th className="text-right text-gray-600 font-medium pb-2">AUC-ROC</th>
                  <th className="text-right text-gray-600 font-medium pb-2">Precision</th>
                  <th className="text-right text-gray-600 font-medium pb-2">Recall</th>
                  <th className="text-right text-gray-600 font-medium pb-2">F1</th>
                </tr>
              </thead>
              <tbody>
                {baselineModels.map((m) => (
                  <tr key={m.model} className={`border-b border-gray-100 ${m.highlight ? 'bg-brand-400/5' : ''}`}>
                    <td className={`py-2.5 ${m.highlight ? 'text-brand-400 font-medium' : 'text-gray-600'}`}>{m.model}</td>
                    <td className="text-right text-gray-700 font-mono">{m.auc}</td>
                    <td className="text-right text-gray-700 font-mono">{m.precision}</td>
                    <td className="text-right text-gray-700 font-mono">{m.recall}</td>
                    <td className="text-right text-gray-700 font-mono">{m.f1}</td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
          <p className="text-[10px] text-gray-600 mt-3 italic">
            XGBoost wins on AUC (threshold-independent ranking quality). The rule-based heuristic
            shows higher F1 at its default cutoff but lower AUC, meaning it&apos;s less flexible to
            tune across operating points.
          </p>
        </div>
      </div>

      {/* ── 4. Go / No-Go Evaluation ── */}
      <div className="bg-gray-50 border border-gray-200 rounded-xl p-5">
        <div className="text-[10px] font-semibold text-brand-400 tracking-wider uppercase mb-1">Go / No-Go Evaluation</div>
        <p className="text-xs text-gray-600 mb-4">Production readiness assessment against minimum thresholds.</p>
        <div className="overflow-x-auto">
          <table className="w-full text-xs">
            <thead>
              <tr className="border-b border-gray-200">
                <th className="text-left text-gray-600 font-medium pb-2">Metric</th>
                <th className="text-left text-gray-600 font-medium pb-2">Target</th>
                <th className="text-left text-gray-600 font-medium pb-2">Actual</th>
                <th className="text-left text-gray-600 font-medium pb-2">Status</th>
              </tr>
            </thead>
            <tbody>
              {goNoGoRows.map((r) => (
                <tr key={r.metric} className="border-b border-gray-100">
                  <td className="py-2.5 text-gray-600">{r.metric}</td>
                  <td className="text-gray-500 font-mono">{r.target}</td>
                  <td className="text-gray-700 font-mono">{r.actual}</td>
                  <td>
                    <span className={`inline-flex items-center gap-1 px-2 py-0.5 rounded-full text-[10px] font-semibold ${
                      r.pass ? 'bg-green-500/10 text-green-600' : 'bg-red-500/10 text-red-600'
                    }`}>
                      <CheckCircle2 className="w-3 h-3" />
                      {r.pass ? 'PASS' : 'FAIL'}
                    </span>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
        <div className="mt-4 pt-3 border-t border-gray-200">
          <span className="inline-flex items-center gap-2 text-sm font-semibold text-green-600">
            <CheckCircle2 className="w-4 h-4" />
            RECOMMENDATION: GO
          </span>
        </div>
      </div>

      {/* ── 5. Business Impact Estimation ── */}
      <div className="bg-gray-50 border border-gray-200 rounded-xl p-5">
        <div className="text-[10px] font-semibold text-brand-400 tracking-wider uppercase mb-1">Business Impact Estimation</div>
        <p className="text-xs text-gray-600 mb-4">Estimated revenue impact from deploying the churn prediction model at scale.</p>
        <div className="grid grid-cols-2 sm:grid-cols-3 lg:grid-cols-4 gap-3">
          {businessMetrics.map((m) => (
            <div key={m.label} className="bg-gray-50 border border-gray-100 rounded-lg p-4">
              <div className="flex items-center gap-2 mb-2">
                <m.icon className="w-3.5 h-3.5 text-brand-400" />
                <span className="text-[10px] text-gray-600">{m.label}</span>
              </div>
              <div className="text-2xl font-bold text-gray-900">{m.value}</div>
              <div className="text-[10px] text-gray-500 mt-1">{m.source}</div>
            </div>
          ))}
        </div>

        {/* Expandable breakdown */}
        <div className="mt-4">
          <button
            onClick={() => setShowBusinessBreakdown(!showBusinessBreakdown)}
            className="flex items-center gap-1.5 text-xs text-brand-400 hover:text-gray-900 transition"
          >
            {showBusinessBreakdown ? <ChevronUp className="w-3.5 h-3.5" /> : <ChevronDown className="w-3.5 h-3.5" />}
            {showBusinessBreakdown ? 'Hide' : 'Show'} full breakdown
          </button>
          {showBusinessBreakdown && (
            <div className="mt-3 bg-gray-50 border border-gray-100 rounded-lg p-4 text-xs text-gray-500 space-y-2">
              <div className="font-medium text-gray-700 mb-2">Revenue Impact Calculation</div>
              <div>1. <span className="text-gray-600">Subscriber base:</span> 95,000,000 (Indosat FY2024 reported subscribers)</div>
              <div>2. <span className="text-gray-600">Monthly churn rate:</span> 3.5% (GSMA Intelligence 2023, Southeast Asia mobile prepaid average)</div>
              <div>3. <span className="text-gray-600">Monthly churners:</span> 95,000,000 x 3.5% = 3,325,000</div>
              <div>4. <span className="text-gray-600">Model recall:</span> 66% of churners correctly identified = 3,325,000 x 0.66 ≈ 2,194,500</div>
              <div>5. <span className="text-gray-600">Retention rate with proactive offer:</span> 25% (industry benchmark for targeted retention campaigns)</div>
              <div>6. <span className="text-gray-600">Subscribers retained/month:</span> 2,194,500 x 25% ≈ 548,625</div>
              <div>7. <span className="text-gray-600">Avg ARPU:</span> $8.50/month (Indosat FY2024 blended ARPU)</div>
              <div>8. <span className="text-gray-600">LTV factor:</span> Partial 12-month lifetime value applied (not full LTV, discounted for re-churn risk)</div>
              <div>9. <span className="text-gray-600">Revenue saved/month:</span> 548,625 x $8.50 x ~0.95 partial factor ≈ $4.4M</div>
              <div>10. <span className="text-gray-600">Annual impact:</span> $4.4M x 12 ≈ $52.7M</div>
              <div className="pt-2 border-t border-gray-100 text-[10px] text-gray-600 italic">
                Note: Actual impact depends on campaign execution quality, offer cost, and churn reason distribution. This is a top-of-funnel estimate.
              </div>
            </div>
          )}
        </div>
      </div>

      {/* ── 6. Edge Cases and Failure Modes ── */}
      <div>
        <div className="text-[10px] font-semibold text-brand-400 tracking-wider uppercase mb-1">Edge Cases and Failure Modes</div>
        <p className="text-xs text-gray-600 mb-4">Scenarios where model performance degrades significantly. Click to expand details.</p>
        <div className="grid grid-cols-1 md:grid-cols-2 gap-3">
          {edgeCases.map((ec, idx) => (
            <div key={idx} className="bg-gray-50 border border-gray-200 rounded-xl overflow-hidden">
              <button
                onClick={() => setExpandedEdgeCase(expandedEdgeCase === idx ? null : idx)}
                className="w-full flex items-center justify-between p-5 text-left hover:bg-gray-50 transition"
              >
                <div className="flex items-center gap-3">
                  <div className="w-8 h-8 rounded-lg bg-red-500/10 flex items-center justify-center flex-shrink-0">
                    <AlertTriangle className="w-4 h-4 text-red-600" />
                  </div>
                  <div>
                    <div className="text-sm font-medium text-gray-800">{ec.title}</div>
                    <div className="text-[10px] text-gray-600">AUC drops to {ec.stress.auc.toFixed(2)}</div>
                  </div>
                </div>
                {expandedEdgeCase === idx ? (
                  <ChevronUp className="w-4 h-4 text-gray-600 flex-shrink-0" />
                ) : (
                  <ChevronDown className="w-4 h-4 text-gray-600 flex-shrink-0" />
                )}
              </button>
              {expandedEdgeCase === idx && (
                <div className="px-5 pb-5 space-y-3 border-t border-gray-100">
                  <p className="text-xs text-gray-500 pt-3">{ec.description}</p>
                  <div className="overflow-x-auto">
                    <table className="w-full text-[11px]">
                      <thead>
                        <tr className="border-b border-gray-200">
                          <th className="text-left text-gray-600 font-medium pb-1.5">Metric</th>
                          <th className="text-right text-gray-600 font-medium pb-1.5">Normal</th>
                          <th className="text-right text-gray-600 font-medium pb-1.5">Stress</th>
                          <th className="text-right text-gray-600 font-medium pb-1.5">Delta</th>
                        </tr>
                      </thead>
                      <tbody>
                        {(['auc', 'precision', 'recall', 'f1'] as const).map((key) => {
                          const label = key === 'auc' ? 'AUC-ROC' : key === 'f1' ? 'F1' : key.charAt(0).toUpperCase() + key.slice(1)
                          const delta = ec.stress[key] - ec.normal[key]
                          return (
                            <tr key={key} className="border-b border-gray-100">
                              <td className="py-1.5 text-gray-500">{label}</td>
                              <td className="text-right text-gray-600 font-mono">{ec.normal[key].toFixed(2)}</td>
                              <td className="text-right text-red-600 font-mono">{ec.stress[key].toFixed(2)}</td>
                              <td className="text-right text-red-600/70 font-mono">{delta.toFixed(2)}</td>
                            </tr>
                          )
                        })}
                      </tbody>
                    </table>
                  </div>
                </div>
              )}
            </div>
          ))}
        </div>
      </div>

      {/* ── 7. Technology Stack ── */}
      <div className="bg-gray-50 border border-gray-200 rounded-xl p-5">
        <div className="text-[10px] font-semibold text-brand-400 tracking-wider uppercase mb-1">Technology Stack</div>
        <p className="text-xs text-gray-600 mb-4">End-to-end platform components powering TelcoPulse AI.</p>
        <div className="overflow-x-auto">
          <table className="w-full text-xs">
            <thead>
              <tr className="border-b border-gray-200">
                <th className="text-left text-gray-600 font-medium pb-2">Component</th>
                <th className="text-left text-gray-600 font-medium pb-2">Technology</th>
              </tr>
            </thead>
            <tbody>
              {techStack.map((t) => (
                <tr key={t.component} className="border-b border-gray-100">
                  <td className="py-2.5 text-gray-600 font-medium">{t.component}</td>
                  <td className="py-2.5 text-gray-500 font-mono text-[11px]">{t.technology}</td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </div>

      {/* ── 8. AI Factory Architecture ── */}
      <div className="bg-gray-50 border border-gray-200 rounded-xl p-5">
        <div className="text-[10px] font-semibold text-brand-400 tracking-wider uppercase mb-1">AI Factory Architecture</div>
        <p className="text-xs text-gray-600 mb-5">End-to-end data flow from ingestion through delivery and feedback loop.</p>
        <div className="flex flex-wrap items-center justify-center gap-y-4 gap-x-1">
          {architectureSteps.map((step, idx) => (
            <div key={step.label} className="flex items-center gap-1">
              <div className="flex flex-col items-center w-[100px]">
                <div className="w-12 h-12 rounded-xl bg-brand-400/10 border border-brand-400/20 flex items-center justify-center mb-2">
                  <step.icon className="w-5 h-5 text-brand-400" />
                </div>
                <div className="text-[10px] font-medium text-gray-700 text-center leading-tight">{step.label}</div>
                <div className="text-[10px] text-gray-600 text-center mt-0.5">{step.desc}</div>
              </div>
              {idx < architectureSteps.length - 1 && (
                <ArrowRight className="w-4 h-4 text-brand-400/40 flex-shrink-0 mt-[-20px]" />
              )}
            </div>
          ))}
        </div>
        <div className="mt-4 flex items-center justify-center gap-2 text-[10px] text-gray-500">
          <RefreshCw className="w-3 h-3" />
          <span>Continuous feedback loop from outcome tracking back to feature engineering and model retraining</span>
        </div>
      </div>
    </div>
  )
}
